// Centralized role permissions for the app

export const ROLE_PERMISSIONS = {
  main: {
    canViewDashboard: true,
    canAddCredits: true,
    canViewAnalytics: true,
    canExportAnalytics: true,
    canView: true,
    canAdd: true,
    canEdit: true,
    canDelete: true,
    canBulkUpload: true,
    canManageGroups: true,
    canManageUsers: true,
    canAccessModals: true,
    canSeeFilters: true,
    canAccessChat: true,
    canSendMessages: true,
    canDeleteChats: true,
    canUseTemplateModal: true,
    canDownloadReports: true,
    canAddBroadcast: true,
    canEditBroadcast: true,
    canDeleteBroadcast: true,
    canViewBroadcast: true,
    canViewTemplates: true,
    canAddTemplate: true,
    canEditTemplate: true,
    canDeleteTemplate: true,
  },
  sub_user: {
    canViewDashboard: true,
    canAddCredits: true,
    canViewAnalytics: true,
    canExportAnalytics: true,
    canView: true,
    canAdd: false, 
    canEdit: false, 
    canDelete: false, 
    canBulkUpload: false,
    canManageGroups: false,
    canManageUsers: false,
    canAccessModals: false,
    canSeeFilters: true,
    canAccessChat: true,
    canSendMessages: true,
    canDeleteChats: false,
    canUseTemplateModal: false,
    canDownloadReports: false,
    canAddBroadcast: false, 
    canViewBroadcast: true,
    canViewTemplates: true,
    canAddTemplate:false,
    canEditTemplate: false,
    canDeleteTemplate: false,
  },
};
